//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18449
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace It.Uniba.Di.Cdg.SocialTfs.ServiceLibrary.StackOverflow {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class StackOverflowUri : global::System.Configuration.ApplicationSettingsBase {
        
        private static StackOverflowUri defaultInstance = ((StackOverflowUri)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StackOverflowUri())));
        
        public static StackOverflowUri Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/2.2/me?filter=!G*lQlKqwAH*.cLrV2K45DsH1BU")]
        public string STACKSCORE {
            get {
                return ((string)(this["STACKSCORE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/2.2/me?filter=!23IiyZnRyYmQ4bPZYWRA1")]
        public string CREDENTIALS {
            get {
                return ((string)(this["CREDENTIALS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/2.2/me/tags?filter=!*MPoAL(IzytfB*M)")]
        public string TAGS {
            get {
                return ((string)(this["TAGS"]));
            }
        }
    }
}
